# Numpy Library Tutorial
***By Alex Borio***



<img src="https://miro.medium.com/max/765/1*cyXCE-JcBelTyrK-58w6_Q.png" alt="350" width="400" align="left"/>

## What is NumPy?
<ul>
<li>NumPy is a Python library used for working with arrays.</li>
<li>It also has functions for working in domain of linear algebra, fourier transform, and matrices.</li>
<li>NumPy was created in 2005 by Travis Oliphant. It is an open source project and you can use it freely.</li>
<li>NumPy stands for Numerical Python.</li>
<li>NumPy is a Python library and is written partially in Python, but most of the parts that require fast computation are written in C or C++.</li>
</ul>

## Why Use NumPy?
<ul>
<li>In Python we have lists that serve the purpose of arrays, but they are slow to process.</li>
<li>NumPy aims to provide an array object that is up to 50x faster than traditional Python lists.</li>
<li>The array object in NumPy is called ndarray, it provides a lot of supporting functions that make working with ndarray very easy.</li>
<li>Arrays are very frequently used in data science, where speed and resources are very important.</li>
</ul>

## Import librerie

In [1]:
import numpy as np

## Introduzione Numpy Ndarray

<img src="https://miro.medium.com/max/831/1*R0wH6D43-rzG7ivvEhSFkA.png" alt="500" width="600" align="left"/>

### Creazione array

In [2]:
arr_1d= np.array([1, 2, 3, 4, 5])

print(arr_1d)

[1 2 3 4 5]


### Creazione di una matrice

In [3]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

print(arr_2d)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## Operazioni con gli array

In [4]:
arr_1d= np.array([1, 2, 3, 4, 5])

In [5]:
arr_1d.ndim #Dimensione

1

In [6]:
arr_1d.size #Numero di elementi

5

In [7]:
arr_1d.min() #Minimo

1

In [8]:
arr_1d.max() #Massimo

5

In [9]:
arr_1d.sum() #Somma

15

## Operazioni con le matrici

In [10]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]])

In [11]:
arr_2d.ndim #Dimensione

2

In [12]:
arr_2d.size #Numero di elementi

12

In [13]:
arr_2d.shape #m rows, n columns (mxn)

(3, 4)

In [14]:
arr_2d.min() #Minimo

arr_2d.max() #Massimo

12

In [15]:
arr_2d.sum() #Somma

78

## Navigare gli array e le matrici

<img src="https://numpy.org/doc/stable/_images/np_matrix_indexing.png" alt="600" width="700" align="left"/>

In [16]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #Matrice

In [17]:
#First element: first row/column (1)
arr_2d[0,0] # [row index, col index]

1

In [18]:
#Only first row
arr_2d[0, :]

array([1, 2, 3, 4])

In [19]:
#Only first column
arr_2d[:,0]

array([1, 5, 9])

## Funzioni Numpy

<img src="https://numpy.org/doc/stable/_images/np_ones_zeros_matrix.png" width="700" align="left"/>

### Funzione zeros() e ones()

Crea un array o una matrice di 0 o 1 della forma che si desidera

In [20]:
np.zeros(2) #Array

array([0., 0.])

In [21]:
np.zeros((3, 4)) #Matrix

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [22]:
np.ones(2) #Array

array([1., 1.])

In [23]:
np.ones((2,2)) #Matrix

array([[1., 1.],
       [1., 1.]])

In [24]:
np.zeros(2, dtype=int) #Array

array([0, 0])

### Funzione random() e randint()

Permette di creare un array con numeri casuali (float o integer)

In [25]:
np.random.random(3) #Return random floats in the half-open interval [0.0, 1.0]

array([0.72260562, 0.4580999 , 0.83344013])

In [26]:
np.random.random((3,2)) #Return random floats matrix with 3 rows and 2 columns

array([[0.47631592, 0.14566367],
       [0.26162667, 0.87366409],
       [0.88325731, 0.48521115]])

In [27]:
minimo=0
massimo=10
numero_elementi=10

arr = np.random.randint(minimo, massimo, numero_elementi)

print('Array di partenza')
print(arr)

Array di partenza
[0 1 0 2 2 7 5 8 8 1]


### Funzione random() distribuzioni statistiche

In [28]:
np.random.seed(1)

print('Estrazione casuale da una gaussiana')
print(np.random.normal(0, 2))  

print('\n')

print('Estrazione casuale da una binomiale')
print(np.random.binomial(5, 0.5)) 

Estrazione casuale da una gaussiana
3.2486907273264833


Estrazione casuale da una binomiale
0


### Funzione choice()

Permette di scegliere un numero in maniera aleatoria all'interno di un array già esistente

In [29]:
arr = np.arange(0,10,1)

print('Array di partenza')
print(arr)
print('\n')
print('Numero estratto')

np.random.choice(arr)

Array di partenza
[0 1 2 3 4 5 6 7 8 9]


Numero estratto


5

### Funzione eye()

<img src="https://www.w3resource.com/w3r_images/numpy-array-eye-function-image-1-b.png" width="200" align="left"/>

In [30]:
np.eye(3) #IDENTITY MATRIX 3x3

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

### Funzione arange()

In [31]:
np.arange(4) #Creare un array con un range di numeri [0, 4 (not included)]

array([0, 1, 2, 3])

In [32]:
inizio = 0
fine = 11
step = 1

x = np.arange(inizio, fine, step)
print('Contenuto array: ')
print(x)
print('\n')
print('Lunghezza  array: ')
print(len(x))
print('\n')
print('Oggetto: ')
print(type(x))

Contenuto array: 
[ 0  1  2  3  4  5  6  7  8  9 10]


Lunghezza  array: 
11


Oggetto: 
<class 'numpy.ndarray'>


### Funzione linspace()

Permette di creare un array con inizio, fine e numero di elementi da inizio a fine

In [33]:
inizio=0
fine=9.5
numero_elementi=20

x = np.linspace(inizio,fine,numero_elementi)
print(x)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


### Funzione reshape()

<img src="https://numpy.org/doc/stable/_images/np_reshape.png" width="600" align="left"/>

In [34]:
arr_2d = np.array([[1, 2, 3, 4], 
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]]) #ARRAY 3X4

arr_2d_res = arr_2d.reshape(4,3) #ARRAY 4X3
print(arr_2d_res)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


### Funzione asarray()

Permette di convertire una lista o una tupla in array

In [35]:
elenco = [0,1,2,3,4]
print(type(elenco))

elenco_array = np.asarray(elenco)
print(type(elenco_array))

<class 'list'>
<class 'numpy.ndarray'>


## Linear Algebra Operations

### Operazioni con array

In [36]:
a = np.array([20, 30, 40, 50])
b = np.arange(0,4,1)

c = a - b #Sottrazione
print('Array C')
print(c)   
print('\n')

d = np.sin(c) #Seno
print('Array D')
print(d)
print('\n')

e = a < 30 #Confronto
print('Array E')
print(e)
print('\n')

f = a * 3 #Moltiplicazione
print('Array F')
print(f)
print('\n')

Array C
[20 29 38 47]


Array D
[ 0.91294525 -0.66363388  0.29636858  0.12357312]


Array E
[ True False False False]


Array F
[ 60  90 120 150]




In [37]:
#Prodotto scalare:

c= np.array([1,0]) 
d= np.array([0,1]) 

e= np.array([1,2,3])
f= np.array([2,4,6]) #combinazione lineare dell'array e (e*2)

#Dot product (prodotto scalare):

print(np.dot(c,d)) # =0 -> prodotto scalare =0, perpendicolari, angolo = 90°
print(np.dot(e,f)) # prodotto scalare positivo & !=0 -> angolo <90°

0
28


### Operazioni con matrici

In [38]:
M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])

#scalar multiplication

M_1 * 10

array([[10, 20],
       [30, 40]])

In [39]:
#Addizione
M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(M_1 + M_2)

[[ 6  8]
 [10 12]]


In [40]:
#PRODOTTO MATRICIALE

M_1 = np.array([[1, 2],  #square matrix 2x2
                [3, 4]])
      
M_2 = np.array([[5, 6],  #square matrix 2x2
                [7, 8]])

print(np.dot(M_1,M_2))   #OUTPUT : square matrix 2x2

[[19 22]
 [43 50]]


In [41]:
M_1= np.array([[1,2,3], #2x3
               [0,1,2]]) 

M_2= np.array([[4,5],   #3x2
               [6,7],
               [8,9]])

print(np.dot(M_1,M_2))  #OUTPUT square matrix: 2x2

[[40 46]
 [22 25]]


# System of linear equations

A system of linear equations (or linear system) is a collection of one or more linear equations involving the same set of variables.

<img src="https://miro.medium.com/max/1400/1*6LRv9DMK9hXvwm5JVpTQuA.png" alt="500" width="600" align="left"/>

In [42]:
a= np.array([[1.50, 0.5], #MATRICE COEFFICIENTI
             [1, 1]])

b= np.array([[78.50], #MATRICE TERMINI NOTI
              [87]])

In [43]:
#Calculate inverse of A

inv_a= np.linalg.inv(a)

In [44]:
ID= a @ inv_a  #identity matrix
ID

array([[1.00000000e+00, 1.11022302e-16],
       [2.22044605e-16, 1.00000000e+00]])

In [45]:
ID_2= np.eye(2)
ID_2

array([[1., 0.],
       [0., 1.]])

In [46]:
np.allclose(ID, ID_2) #confrontiamo le 2 matrici identità solo per sicurezza.

True

In [47]:
X= inv_a @ b #matrice delle Soluzioni (valori incognite)
X

array([[35.],
       [52.]])

In [48]:
#Built in function -> linalg.solve() -> DIRETTAMENTE MATRICE SOLUZIONI

np.linalg.solve(a, b)

array([[35.],
       [52.]])